clone:
  git:
    image: harbor.crystalnet.org/dockerhub-proxy/woodpeckerci/plugin-git:2.4.0
    settings:
      partial: false
      depth: 1

steps:
  docker-build-paperless-ftpd-release:
    image: harbor.crystalnet.org/dockerhub-proxy/woodpeckerci/plugin-docker-buildx:2.2.1
    settings:
      repo: harbor.crystalnet.org/library/paperless-ftpd
      logins:
      - registry: https://harbor.crystalnet.org/
        username: robot$library+woodpecker
        password:
          from_secret: harbor_token
      registry: harbor.crystalnet.org
      auto_tag: true
      dockerfile: paperless-ftpd/Dockerfile
      context: paperless-ftpd
      platforms: linux/amd64,linux/i386,linux/arm64/v8,linux/arm/v7
      dry_run: false
    when:
    - path: 'paperless-ftpd/*'
when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: tag