steps:
  docker-build-proftpd-dev:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: harbor.crystalnet.org/library/proftpd
      logins:
      - registry: https://harbor.crystalnet.org/
        username: robot$library+woodpecker
        password:
          from_secret: harbor_token
      registry: harbor.crystalnet.org
      tags: dev
      dockerfile: proftpd/Dockerfile
      context: proftpd
      platforms: linux/amd64,linux/i386,linux/arm64/v8,linux/arm/v7
      dry_run: false
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
  docker-build-proftpd-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: harbor.crystalnet.org/library/proftpd
      logins:
      - registry: https://harbor.crystalnet.org/
        username: robot$library+woodpecker
        password:
          from_secret: harbor_token
      registry: harbor.crystalnet.org
      auto_tag: true
      dockerfile: proftpd/Dockerfile
      context: proftpd
      platforms: linux/amd64,linux/i386,linux/arm64/v8,linux/arm/v7
      dry_run: false
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: tag