clone:
  git:
    image: woodpeckerci/plugin-git

steps:
  renovate:
    image: renovate/renovate:35.14.4
    secrets: 
      - github_com_token
    environment:
      - RENOVATE_CONFIG_FILE=.woodpecker/renovate_config.json
      - RENOVATE_DRY_RUN=true
    commands:
      - echo ${GITHUB_COM_TOKEN}
      - renovate --platform github --git-author "Renovate <renovate@local.bot>" --ignore-pr-author true
when:
  event: [cron, manual]
  branch: main