clone:
  git:
    image: woodpeckerci/plugin-git

steps:
  renovate:
    image: dekulow/node-renovate:35.15.0@sha256:0bee375126f16fa095c7819598a3f070a799f734d1b3b9e22040fbfdeca5a672
    environment:
      - RENOVATE_CONFIG_FILE=.woodpecker/renovate_config.json
    commands:
      - renovate --platform github --ignore-pr-author true
when:
  event: [cron, manual]
  branch: main