clone:
  git:
    image: woodpeckerci/plugin-git

steps:
  renovate:
    image: renovate/renovate:35.14.4
    environment:
      - RENOVATE_CONFIG_FILE=.woodpecker/renovate_config.json
    commands:
      - renovate --platform github --ignore-pr-author true
when:
  event: [cron, manual]
  branch: main