clone:
  git:
    image: woodpeckerci/plugin-git

steps:
  renovate:
    image: renovate/renovate:35.14.4
    secrets: 
      - github_com_token
    environment:
      - RENOVATE_CONFIG_FILE=.woodpecker/renovate_config.json
      - RENOVATE_GIT_AUTHOR="Renovate <renovate@local.bot>"
      - RENOVATE_DRY_RUN=true
    commands:
      - renovate --platform github --git-author "${RENOVATE_GIT_AUTHOR}" --ignore-pr-author true
when:
  event: [cron, manual]
  branch: main